name: Arm build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@users/ericsciple/m167instead_impl
      with:
        submodules: true
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4'
    - name: make
      run: make -C boost_g474
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: bort2.elf
        path: boost_g474/build/bort2.elf
