name: Arm build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install dfu-suffix
      run: sudo apt-get install -y dfu-util
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: arm-none-eabi-gcc
      timeout-minutes: 10
      uses: fiam/arm-none-eabi-gcc@master
      with:
        release: '9-2020-q2'
    - name: make boost
      run: make -C boost_g474
    - name: make fabulab
      run: make -C fabulab_f446
    - name: make freebot
      run: make -C freebot_g474
    - name: Archive freebot
      uses: actions/upload-artifact@v2
      with:
        name: freebot_g474
        path: |
          freebot_g474/build/freebot_g474.elf
          freebot_g474/build/freebot_g474.bin
    - name: Archive boost
      uses: actions/upload-artifact@v2
      with:
        name: boost_weight
        path: |
          boost_g474/build/weight.elf
          boost_g474/build/weight.tgz
    - name: Archive fabulab
      uses: actions/upload-artifact@v2
      with:
        name: fabulab_f446
        path: |
          fabulab_f446/build/fabulab_f446.elf
          fabulab_f446/build/fabulab_f446.bin