name: Arm build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: boost_g474
            config: pz
          - project: fabulab_f446
          - project: freebot_g474
            config: motor_enc
          - project: freebot_g474
            config: motor_wheel
    runs-on: ubuntu-latest
    steps:
    - name: install dfu-suffix
      run: sudo apt-get install -y dfu-util
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: arm-none-eabi-gcc
      timeout-minutes: 10
      uses: fiam/arm-none-eabi-gcc@master
      with:
        release: '9-2020-q2'
      if: matrix.config
    - name: make ${{ matrix.project }} ${{ matrix.config }}
      run: make -C ${{ matrix.project }} CONFIG=${{ matrix.config }} -j2
    - name: Archive ${{ matrix.project }} ${{ matrix.config }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.project }} ${{ matrix.config }}
        path: |
          ${{ matrix.project }}/build/${{ matrix.config }}.elf
          ${{ matrix.project }}/build/${{ matrix.config }}.tgz
      if: !matrix.config
    - name: make ${{ matrix.project }}
      run: make -C ${{ matrix.project }}$ -j2
    - name: Archive ${{ matrix.project }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.project }}
        path: |
          ${{ matrix.project }}/build/${{ matrix.project }}.elf
          ${{ matrix.project }}/build/${{ matrix.project }}.tgz