name: Arm build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: arm-none-eabi-gcc
      timeout-minutes: 10
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4'
    - name: make
      run: make -C boost_g474
    - name: make2
      run: make -C fabulab_f446
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: boost_g474.elf
        path: boost_g474/build/bort2.elf
    - name: Archive production artifacts2
      uses: actions/upload-artifact@v1
      with:
        name: fabulab_f446.elf
        path: fabulab_f446/build/fabulab_f446.elf
    - name: make3
      run: make -C freebot_g474
    - name: Archive production artifacts3
      uses: actions/upload-artifact@v1
      with:
        name: freebot_g474.elf
        path: freebot_g474/build/freebot_g474.elf
        name: freebot_g474.bin
        path: freebot_g474/build/freebot_g474.bin
